### ISSUE TITLE
Adding extra dashes and vertical lines will still generate a xml

### ISSUE THREAD

**Issue by mike-jshen** [Deys2000/actual-EECS2311Group15#26]
Report by: Mike Shen 216353583

Group 15 Bug Reports

Version: 044304c

Tested on: Windows 10 Java SE 1.8

Bug Report #1: Adding extra dashes and vertical lines will still generate a xml

Severity: Medium (XML outputs are still generated)

Description:
When adding extra spaces beyond the standard guitar tab, we see that an xml is generated instead of an error message. 

Comments:
It seems that when you remove lines below the limit, an error message pops up but adding extra lines to the tab will not.

Attachments:
![image](https://user-images.githubusercontent.com/68671792/112414056-c67fb100-8cf7-11eb-9955-da33e6b0f3e5.png)

![image](https://user-images.githubusercontent.com/68671792/112414061-ca133800-8cf7-11eb-8512-09f5546380c1.png)

**Comment by ennorom** [comment]
Hi Mike, 

Thanks for pointing that out. However, the issue you pointed out was done by design in that version of our release. We wanted our application to work even when there is a small error and so we decided that having a few extra characters is not big enough to stop translation but having a few less characters in a line is significant enough to stop the translation. In future releases we will work towards having a warning message in both situations I mentioned.

Regards,
Elijah
